#' ---
#' title: "Overview of Ripcord"
#' author: "Alex F. Bokov"
#' output:
#'   html_document:
#'     toc: true
#'     toc_float: true
#' ---
#' 
#+ setup, echo=FALSE, message=FALSE, warning=FALSE,results='hide'
.projpackages <- c('');
.deps <- c( 'prep_deps.R' ); 
# do not edit the next two lines
.junk<-capture.output(source('./scripts/global.R',chdir=TRUE,echo=FALSE));
.currentscript <- current_scriptname('overview.R');
#+ echo=FALSE, results='hide'
#' ## Introduction
#' 
#' Welcome to Ripcord-- a framework for rapidly setting up data science projects
#' in an automated and reproducible manner. The main data analysis example file
#' is [`example_analysis.html`](example_analysis.html) which was generated by 
#' [`example_analysis.R`](example_analysis.R). This and other scripts here are
#' ordinary R scripts-- anything you can do to an R script you can do to these.
#' But our R scripts have the following additional features:
#' 
#' 1. They delegate certain tasks to scripts in the [`scripts`](scripts) directory, 
#'    which include loading/interpreting data files and keeping track of
#'    which libraries are needed. Read more about them below in 
#'    'The `scripts` directory' section.
#' 2. These scripts have a standardized way of specifying what other scripts
#'    they depend on, and a standardized way of saving their data so that other
#'    scripts can depend on them in turn. Read more about them below.
#' 3. These scripts use two shared configuration files: [`config.R`](config.R) for
#'    public project-level settings and [`local.config.R`](local.config.R) for 
#'    local project-level settings. These are the only places where you need to
#'    specify the location of your data files-- all the other scripts here will 
#'    automatically find them.
#' 
#' ## The project directory
#' 
#' In addition to [`example_analysis.R`](example_analysis.R) which attemtps to
#' (randomly) select valid variables from your data and do example analysis of
#' them, there is also [`minimum_scriport.R`](minimum_scriport.R) which is blank
#' except a few lines of code at the beginning and end that give it access to
#' Ripcord's features and a few explanatory comments.
#' 
#' _more coming soon_
#' 
#' ## The `scripts` directory
#' 
#' _coming soon_
#' 
#+ echo=FALSE, results='hide'
save(file=paste0(.currentscript,'.rdata'),list=setdiff(ls(),.origfiles));
c()

